name: blurry_artist_details_page
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  url_launcher: ^3.0.2
  flutter_radio: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/fondo1.png
  - assets/fondo2.jpg
  - assets/fondo3.jpg
  - assets/fondo4.jpg
  - assets/fondo5.jpg
  - assets/fondo6.jpg
  - assets/fondo7.jpg
  - assets/logo1.jpg
  - assets/video1.jpg
  - assets/video2.jpg
  - assets/video3.jpg
  - assets/video4.jpg
  - assets/imagen1.jpg